export const reminder = [
  "Success is not a destination but a journey—stay focused, work hard, and let your scores be a reflection of your determination.",
  "Embrace the challenges, for they are stepping stones to greatness—your hard work will pave the way to outstanding scores.",
  "Stay committed to your goals, even when the path seems daunting—remember, each score is a testament to your resilience.",
  "Rise above the distractions and dedicate yourself to excellence—your scores will be a testament to your unwavering focus.",
  "Believe in your abilities and unleash the power within you—let your scores showcase the brilliance of your efforts.",
  "Embrace each test as an opportunity to shine—your scores will be a testament to your dedication and preparation.",
  "Every question is an opportunity to showcase your knowledge and skills—let your scores be a reflection of your brilliance.",
  "Embrace the thrill of the challenge and let it ignite a fire within you—your scores will soar as you push your limits.",
  "Stay motivated, stay focused, and let your scores be a testament to your unwavering commitment to excellence.",
  "Don't be discouraged by setbacks—use them as fuel to propel you forward and achieve remarkable scores.",
  "In the face of adversity, remember your resilience—your scores will be a testament to your ability to overcome.",
  "Trust in your abilities and let your hard work translate into remarkable scores that exceed your expectations.",
  "Stay determined, stay disciplined, and let your scores be a reflection of your unwavering commitment to success.",
  "Remember that hard work and dedication are the keys that unlock the doors to extraordinary scores.",
  "Don't settle for mediocrity—push yourself to new heights and watch your scores skyrocket.",
  "Celebrate the small victories along the way—they are stepping stones to achieving the scores you desire.",
  "Visualize success, work diligently, and watch your scores transform into a true reflection of your capabilities.",
  "Don't let self-doubt dim your light—embrace your potential and let your scores shine as a testament to your brilliance.",
  "Stay persistent, stay focused, and let your scores become a testament to the power of unwavering determination.",
  "Embrace the challenges with a warrior's spirit—let your scores be a testament to your resilience and perseverance.",
  "Believe in yourself, trust in your abilities, and watch your scores become a testament to your unwavering confidence.",
  "Treat each test as an opportunity to showcase your growth and progress—let your scores tell the story of your journey.",
  "Remember, the greatest scores are often achieved by those who are willing to go the extra mile and give it their all.",
  "Just as a drop of water creates ripples in a pond, your task has the power to create a ripple effect of positive change.",
  "The task at hand is a gift—a chance to leave your mark on the world, no matter how small.",
  "Nurture your task like a tender seed, for it has the potential to grow into a flourishing garden of success.",
  "The task before you is a blank canvas; dip your brush into the colors of your potential and paint a vibrant picture.",
  "Each task is an opportunity to learn, grow, and unveil the infinite potential within you.",
  "The symphony of productivity beckons you; find harmony within your task and create a masterpiece.",
  "Task by task, you weave the tapestry of your success; ensure each thread is woven with care.",
  "Embrace the beauty of your task as it unfolds, and let each step be a brushstroke in your masterpiece.",
  "Success is not final, failure is not fatal: It is the courage to continue that counts. - Winston Churchill",
  "Stay focused, stay determined, and success will become an inevitable part of your journey",
  '"Success is not in what you have, but who you are." - Bo Bennett',
  '"Success is not the key to happiness. Happiness is the key to success. If you love what you are doing, you will be successful." - Albert Schweitzer',
  'Believe in yourself and your abilities, for success is born from self-confidence and unwavering determination.',
  'Dare to dream, have the courage to act, and success will follow you like a faithful companion.',
  'Stay committed to your goals, stay hungry for knowledge, and success will be the sweetest reward.',
  'Let your passion be the driving force behind your journey towards success—the world is waiting for your greatness.',
  'Success is not limited by circumstances; it is forged by the choices you make and the actions you take.',
  'Rise above the doubts and embrace the challenges, for success lies on the other side of fear.',
  '"Success is not the key to happiness. Happiness is the key to success. If you love what you are doing, you will be successful." - Buddha',
  "Be grateful for what you have. It's easy to focus on the things we don't have, but when we take the time to appreciate the good things in our lives, it helps us to feel happier and more content.",
  "Help others. One of the best ways to find happiness is to help others. When we give of ourselves, it makes us feel good and connected to something larger than ourselves.",
  "Follow your dreams. Don't be afraid to go after what you want in life. If you have a dream, don't give up on it. Work hard and never give up on yourself.",
  "Be positive. A positive attitude can go a long way in helping you achieve happiness and success. When you focus on the good things in life and believe in yourself, you're more likely to succeed.",
  "Don't give up. There will be times when you want to give up. But if you keep going, you will eventually achieve your goals.",
  "It's okay to feel lonely and upset. Everyone feels these emotions from time to time. It's important to acknowledge your feelings and allow yourself to feel them.",
  "Take care of yourself. Make sure you're getting enough sleep, eating healthy foods, and exercising regularly. When you take care of your physical and mental health, you're better able to handle the challenges of life.",
  "Challenge negative thoughts—replace self-criticism with positive affirmations and cultivate a mindset of self-empowerment.",
  "Remember that happiness is a journey—be patient with yourself, and know that brighter days are ahead.",
  "Explore new connections and social opportunities—join clubs, organizations, or virtual communities that align with your interests.",
  "Practice gratitude—remind yourself of the things you are grateful for, even in the midst of difficult times.",
  "Look for opportunities to help others—acts of kindness and compassion can bring immense joy and fulfillment.",
  "Take breaks from social media—limit your screen time and focus on real-life connections and experiences."
];
